### ISSUE TITLE
Can I run this on my Mac with Intel Iris Graphics 6100 GPU?

### ISSUE THREAD

**Issue by kaiwaehner** [zhengyima/DeepNude_NoWatermark_withModel#16]
I get the following exception. Can I just install an Nvidia driver on my Mac or can I run it with CPU or do I have to start a cloud instance which has the right GPU?

⇒  docker run --rm -it -v $PWD:/app:rw ababy/python-deepnude /bin/bash
Unable to find image 'ababy/python-deepnude:latest' locally
latest: Pulling from ababy/python-deepnude
6f2f362378c5: Pull complete 
494c27a8a6b8: Pull complete 
7596bb83081b: Pull complete 
372744b62d49: Pull complete 
615db220d76c: Pull complete 
39aa0c89bda1: Pull complete 
da1dae8da560: Pull complete 
3b8162139e71: Pull complete 
f94aa49947d3: Pull complete 
8f1f89c2ca6c: Pull complete 
0558c2c7813d: Pull complete 
Digest: sha256:3d7571ee8c4e10de2dca840b57cb4ffaaf35503182c0b8884aec4760ce7c76fc
Status: Downloaded newer image for ababy/python-deepnude:latest
root@c5469230c05e:/app# python main.py
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main(inputpath, outputpath)
  File "main.py", line 26, in main
    watermark = process(dress)
  File "/app/run.py", line 115, in process
    model.initialize(opt)
  File "/app/gan.py", line 68, in initialize
    opt.n_blocks_local, opt.norm, self.gpu_ids)        
  File "/app/gan.py", line 117, in __define_G
    netG.cuda(gpu_ids[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from

**Comment by zhengyima** [comment]
You can try... If still error, u can use your CPU，which is not too slow compared to cpu :)

**Comment by kaiwaehner** [comment]
@zhengyima I am fine with CPU. However, what do I need to change in the code to use my CPU? 

Right now it tries to use a GPU, therefore I get the error.

**Comment by zhengyima** [comment]
> @zhengyima I am fine with CPU. However, what do I need to change in the code to use my CPU?
> 
> Right now it tries to use a GPU, therefore I get the error.

You can check the readme.md. There is a chapter about how to use cpu. You should modify the code in gan.py :)

**Comment by kaiwaehner** [comment]
Damn. Sometimes you need to read the full readme :-) Thanks.

Now getting another exception, but I will try your recommended way in the readme of using conda to create a new environment.
