### ISSUE TITLE
I meet a error

### ISSUE THREAD

**Issue by HJMRX** [zhengyima/DeepNude_NoWatermark_withModel#31]
At first, after configuring the environment according to the document, but prompted that there was no `cv'module running main, I installed `opencv' with `conda', but there was still a mistake. Is the pytorch version wrong?

(deepnnde) F:\Deepnnde\DeepNude_NoWatermark_withModel>python main.py
Processing input.png
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "main.py", line 46, in deep_nude_process
    watermark = process(dress)
  File "F:\Deepnnde\DeepNude_NoWatermark_withModel\run.py", line 115, in process
    model.initialize(opt)
  File "F:\Deepnnde\DeepNude_NoWatermark_withModel\gan.py", line 68, in initialize
    opt.n_blocks_local, opt.norm, self.gpu_ids)
  File "F:\Deepnnde\DeepNude_NoWatermark_withModel\gan.py", line 117, in __define_G
    netG.cuda(gpu_ids[0])
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "F:\Anaconda\envs\deepnnde\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by zhengyima** [comment]
像是你机器的gpu配置有问题，用cpu吧
