### ISSUE TITLE
麻烦请教一下这个'NoneType' object has no attribute 'pydev_notify_kill'问题

### ISSUE THREAD

**Issue by Wang-Senhai** [zhengyima/DeepNude_NoWatermark_withModel#32]
```python
Traceback (most recent call last):
  File "/Users/luke_hai/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
    py_db.notify_thread_not_alive(get_current_thread_id(t))
  File "/Users/luke_hai/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
    was_notified = thread.additional_info.pydev_notify_kill
AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
Terminated: 15
```
这是什么情况啊？
是我的环境有问题吗？

**Comment by zhengyima** [comment]
这个问题不会搞= =

**Comment by zhengyima** [comment]
看起来像是python装的有问题

**Comment by ray1422** [comment]
問題是 thread.additional_info 回傳了None了
