### ISSUE TITLE
[Errno 2] No such file or directory: 'xdg-open': 'xdg-open'

### ISSUE THREAD

**Issue by XinStar1** [zhengyima/DeepNude_NoWatermark_withModel#35]
你好，我按照readme在MacBook Pro上进行docker一键安装之后，运行程序出现如下error：

Executing phase: nude_to_watermark
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 38, in main
    open_file(outputpath)
  File "main.py", line 24, in open_file
    subprocess.call([opener, filepath])
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'

我在网上查到有说是因为没有安装xdg-utils，于是通过macports安装了xdg-utils，不过再次运行还是会出现上述结果。
因为本人接触这块不久，还是新手，特此向大神们请教

**Comment by Naim120** [comment]
@XinStar1  how did u solve it? I am having the same problem

**Comment by 5MinHi** [comment]
同样的问题，请问怎么解决的
