### ISSUE TITLE
报错？

### ISSUE THREAD

**Issue by MX-Qulin** [zhengyima/DeepNude_NoWatermark_withModel#39]
Processing input.png
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "main.py", line 46, in deep_nude_process
    watermark = process(dress)
  File "/app/run.py", line 115, in process
    model.initialize(opt)
  File "/app/gan.py", line 68, in initialize
    opt.n_blocks_local, opt.norm, self.gpu_ids)        
  File "/app/gan.py", line 117, in __define_G
    netG.cuda(gpu_ids[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by zhengyima** [comment]
GPU配置有问题，改用cpu吧。

**Comment by MX-Qulin** [comment]
好的 谢谢您

**Comment by MX-Qulin** [comment]
如何设置使用CPU/GPU?

**Comment by zhengyima** [comment]
README中有写，改gan.py中的self.gpu_ids就可以了。
