### ISSUE TITLE
环境按照readme配置以后运行出现这个错误

### ISSUE THREAD

**Issue by geekAKStar** [zhengyima/DeepNude_NoWatermark_withModel#4]
(deepnude) ➜  DeepNude_NoWatermark_withModel git:(master) ✗ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from run import process
  File "/me/python/DeepNude_NoWatermark_withModel/run.py", line 4, in <module>
    from gan import DataLoader, DeepModel, tensor2im
  File "/me/python/DeepNude_NoWatermark_withModel/gan.py", line 4, in <module>
    import torchvision.transforms as transforms
  File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/models/__init__.py", line 1, in <module>
    from .alexnet import *
  File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 1, in <module>
    import torch.nn as nn
  File "/me/python/DeepNude_NoWatermark_withModel/torch/__init__.py", line 79, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

**Comment by zhengyima** [comment]
自行Google或百度一下，应该是自己机器环境的问题。帮你搜了几个链接：

**Comment by zhengyima** [comment]
> (deepnude) ➜ DeepNude_NoWatermark_withModel git:(master) ✗ python main.py
> Traceback (most recent call last):
> File "main.py", line 4, in 
> from run import process
> File "/me/python/DeepNude_NoWatermark_withModel/run.py", line 4, in 
> from gan import DataLoader, DeepModel, tensor2im
> File "/me/python/DeepNude_NoWatermark_withModel/gan.py", line 4, in 
> import torchvision.transforms as transforms
> File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/**init**.py", line 1, in 
> from torchvision import models
> File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/models/**init**.py", line 1, in 
> from .alexnet import *
> File "/anaconda3/envs/deepnude/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 1, in 
> import torch.nn as nn
> File "/me/python/DeepNude_NoWatermark_withModel/torch/**init**.py", line 79, in 
> from torch._C import *
> ModuleNotFoundError: No module named 'torch._C'

自行Google或百度一下吧，应该是自己机器环境的问题。

帮你搜了几个链接：

[](https://www.cnblogs.com/jourluohua/p/9735846.html)
[](https://stackoverflow.com/questions/50203945/no-module-named-torch-or-torch-c)
[](https://blog.csdn.net/sparkexpert/article/details/77675581)

Good Luck :)
