### ISSUE TITLE
Colab problem

### ISSUE THREAD

**Issue by burninglay** [zhengyima/DeepNude_NoWatermark_withModel#51]
bro,when I tried on google colab,run main.py:

Processing input.png
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Executing phase: maskref_to_maskdet
Executing phase: maskdet_to_maskfin
Executing phase: maskfin_to_nude
Executing phase: nude_to_watermark
Error: no "view" mailcap rules found for type "image/png"
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'output.png'

**Comment by burninglay** [comment]
Processing input.png
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "main.py", line 43, in deep_nude_process
    h = dress.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by strannick-ru** [comment]
Just install any browser.
`apt install lynx`
