### ISSUE TITLE
No such file or directory: 'checkpoints/cm.lib'

### ISSUE THREAD

**Issue by N3xIALIST** [zhengyima/DeepNude_NoWatermark_withModel#55]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "main.py", line 46, in deep_nude_process
    watermark = process(dress)
  File "C:\Users\Ghaz\AppData\Roaming\Adobe\Flash Player\DeepNude_NoWatermark_withModel-master\run.py", line 115, in process
    model.initialize(opt)
  File "C:\Users\Ghaz\AppData\Roaming\Adobe\Flash Player\DeepNude_NoWatermark_withModel-master\gan.py", line 71, in initialize
    self.__load_network(self.netG)
  File "C:\Users\Ghaz\AppData\Roaming\Adobe\Flash Player\DeepNude_NoWatermark_withModel-master\gan.py", line 93, in __load_network
    network.load_state_dict(torch.load(save_path))
  File "C:\Users\Ghaz\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Ghaz\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Ghaz\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

**Comment by paulmcq** [comment]
Download the models before running. See **Models** section in README_EN
