### ISSUE TITLE
a bug that appears when the program starts.

### ISSUE THREAD

**Issue by Absolut3** [zhengyima/DeepNude_NoWatermark_withModel#56]
user@O:~/apps/DeepNude_NoWatermark_withModel$ python3 main.py
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/home/user/apps/DeepNude_NoWatermark_withModel/run.py", line 115, in process
    model.initialize(opt)
  File "/home/user/apps/DeepNude_NoWatermark_withModel/gan.py", line 69, in initialize
    self.__load_network(self.netG)
  File "/home/user/apps/DeepNude_NoWatermark_withModel/gan.py", line 89, in __load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/user/.local/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/user/.local/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/user/.local/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

**Comment by paulmcq** [comment]
Probably a duplicate of #55. Download the models before executing. See **MODELS** section of README_EN
