### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by DebbySaurus** [zhengyima/DeepNude_NoWatermark_withModel#58]
Processing input.png
Traceback (most recent call last):
  File "I:\DNs\Deepnude\main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "I:\DNs\Deepnude\main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "I:\DNs\Deepnude\main.py", line 43, in deep_nude_process
    h = dress.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

Am I doing something wrong or is there an error in the script?

**Comment by guanw666** [comment]
your file path have problem
