### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

### ISSUE THREAD

**Issue by NagromW** [zhengyima/DeepNude_NoWatermark_withModel#64]
Hey, found an error, not entirely sure what I'm doing wrong - all the packages are installed correctly. First time run.

```
Processing input.png
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "C:\Users\-----\Desktop\Scripts\deepnude\main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "C:\Users\-----\Desktop\Scripts\deepnude\main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "C:\Users\-----\Desktop\Scripts\deepnude\main.py", line 46, in deep_nude_process
    watermark = process(dress)
  File "C:\Users\-----\Desktop\Scripts\deepnude\run.py", line 115, in process
    model.initialize(opt)
  File "C:\Users\-----\Desktop\Scripts\deepnude\gan.py", line 71, in initialize
    self.__load_network(self.netG)
  File "C:\Users\-----\Desktop\Scripts\deepnude\gan.py", line 93, in __load_network
    network.load_state_dict(torch.load(save_path))
  File "C:\Users\-----\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\-----\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'
```

**Comment by NagromW** [comment]
Fixed the issue, I didn't read the sections stating to make a directory in cwd:

`you should download the three .lib files before running the program. Then create a dir named 'checkpoints' under the root dir of the project. Put the three downloaded files to the 'checkpoints' dir`
