### ISSUE TITLE
findDecoder imread_('input.png'): can't open/read file

### ISSUE THREAD

**Issue by keyvanlp** [zhengyima/DeepNude_NoWatermark_withModel#66]
Processing input.png
[ WARN:0@1.112] global loadsave.cpp:244 cv::findDecoder imread_('input.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\Administrator\deepnude\main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "C:\Users\Administrator\deepnude\main.py", line 35, in main
    watermark = deep_nude_process(inputpath)
  File "C:\Users\Administrator\deepnude\main.py", line 43, in deep_nude_process
    h = dress.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

this error appears when i type "python main.py"

**Comment by Sabbir328** [comment]
![CC78BE93-2BAB-48E0-8AC9-9B38C80FF7E0](https://user-images.githubusercontent.com/118660432/217358044-3ed8a496-ba63-471c-b1f9-119cd27b531b.jpeg)

**Comment by Sabbir328** [comment]
Make it nude girl
