### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ucas010** [zhengyima/DeepNude_NoWatermark_withModel#69]
```
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    main()
  File "main.py", line 22, in main
    watermark = process(dress)
  File "deepnude_official/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "deepnude_official/opencv_transform/mask_to_maskref.py", line 38, in create_maskref
    res2 = cv2.bitwise_and(green, green, mask = green_mask)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/core/src/arithm.cpp:250: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

```

**Comment by ucas010** [comment]
got[ answer](https://github.com/zhengyima/DeepNude_NoWatermark_withModel/issues/5)
but the result is bullshit, 10 imgs' results no one could be appreciated

**Comment by ucas010** [comment]
could not get the similar result of the official 
and the [news](https://finance.sina.cn/2023-03-29/detail-imynppre8230677.d.html)
