### ISSUE TITLE
No such file or directory: 'xdg-open': 'xdg-open'   anyone can help me

### ISSUE THREAD

**Issue by Haiyang-coder** [zhengyima/DeepNude_NoWatermark_withModel#72]
Processing input.png
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Executing phase: maskref_to_maskdet
Executing phase: maskdet_to_maskfin
Executing phase: maskfin_to_nude
Executing phase: nude_to_watermark
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(inputpath, outputpath, show)
  File "main.py", line 38, in main
    open_file(outputpath)
  File "main.py", line 24, in open_file
    subprocess.call([opener, filepath])
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'

**Comment by Haiyang-coder** [comment]
can not find the xdg-open
