### ISSUE TITLE
提示nvdia驱动不存在, 我用github的另外一个仓库的项目, 则正常

### ISSUE THREAD

**Issue by fizzday** [zhengyima/DeepNude_NoWatermark_withModel#8]
root@265fe3fa7b79:/app/DeepNude_NoWatermark_withModel# python main.py 
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main2()
  File "main.py", line 17, in main2
    watermark = process(dress)
  File "/app/DeepNude_NoWatermark_withModel/run.py", line 115, in process
    model.initialize(opt)
  File "/app/DeepNude_NoWatermark_withModel/gan.py", line 66, in initialize
    opt.n_blocks_local, opt.norm, self.gpu_ids)        
  File "/app/DeepNude_NoWatermark_withModel/gan.py", line 113, in __define_G
    netG.cuda(gpu_ids[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by zhengyima** [comment]
> root@265fe3fa7b79:/app/DeepNude_NoWatermark_withModel# python main.py
> libpng warning: iCCP: known incorrect sRGB profile
> Executing phase: dress_to_correct
> Executing phase: correct_to_mask
> Traceback (most recent call last):
> File "main.py", line 45, in 
> main2()
> File "main.py", line 17, in main2
> watermark = process(dress)
> File "/app/DeepNude_NoWatermark_withModel/run.py", line 115, in process
> model.initialize(opt)
> File "/app/DeepNude_NoWatermark_withModel/gan.py", line 66, in initialize
> opt.n_blocks_local, opt.norm, self.gpu_ids)
> File "/app/DeepNude_NoWatermark_withModel/gan.py", line 113, in __define_G
> netG.cuda(gpu_ids[0])
> File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
> return self._apply(lambda t: t.cuda(device))
> File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
> module._apply(fn)
> File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
> module._apply(fn)
> File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
> param.data = fn(param.data)
> File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in 
> return self._apply(lambda t: t.cuda(device))
> File "/usr/local/lib/python3.7/site-packages/torch/cuda/**init**.py", line 162, in _lazy_init
> _check_driver()
> File "/usr/local/lib/python3.7/site-packages/torch/cuda/**init**.py", line 82, in _check_driver
> http://www.nvidia.com/Download/index.aspx""")
> AssertionError:
> Found no NVIDIA driver on your system. Please check that you
> have an NVIDIA GPU and installed a driver from
> http://www.nvidia.com/Download/index.aspx

这应该不是代码的问题，更可能是机器本身环境的问题，所以有些无能为力。确定一下GPU能不能用？实在不行用CPU也可以，速度没有差很多 :)
